{% set name = "ctapipe_io_lst" %}
{% set version = "0.22.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ctapipe_io_lst-{{ version }}.tar.gz
  sha256: b9c0adac389571e85223a39743d1ff29b47f3648988dceab67ced667eed08c47

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm
  run:
    - python >=3.8
    - astropy >=5.2,<6.dev0
    - ctapipe >=0.19.0,<0.21.0.dev0
    - protozfits >=2.2,<3.dev0
    - numpy >=1.20

test:
  imports:
    - ctapipe_io_lst
  commands:
    - pip check
    # check setuptools_scm provided a version
    - python -c "from ctapipe_io_lst import __version__; print(__version__)" | grep -v 0.0.0
    # check our event source is findable by ctapipe
    - python -c 'from ctapipe.io import EventSource; print(EventSource.non_abstract_subclasses())' | grep LSTEventSource

  requires:
    - pip

about:
  home: https://pypi.org/project/ctapipe-io-lst/
  summary: ctapipe plugin for reading LST prototype files
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maxnoe
    - moralejo
