{% set name = "ctapipe_io_lst" %}
{% set version = "0.27.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ctapipe_io_lst-{{ version }}.tar.gz
  sha256: 278921cb6d9719879f77c9c6cd7a32322a278e539183f44cf4b0b39b097fb9c6

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - astropy-base >=5.2,<8.0.0.dev0
    - ctapipe >=0.23.2,<0.27.0.dev0
    - protozfits >=2.6,<3.dev0
    - numpy >=1.20
    - scipy

test:
  imports:
    - ctapipe_io_lst
  commands:
    - pip check
    # check setuptools_scm provided a version
    - python -c "from ctapipe_io_lst import __version__; print(__version__)" | grep -v 0.0.0
    # check our event source is findable by ctapipe
    - python -c 'from ctapipe.io import EventSource; print(EventSource.non_abstract_subclasses())' | grep LSTEventSource

  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/ctapipe-io-lst/
  summary: ctapipe plugin for reading LST prototype files
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maxnoe
    - moralejo
