{% set name = "ctapipe_io_lst" %}
{% set version = "0.26.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ctapipe_io_lst-{{ version }}.tar.gz
  sha256: 04d09fff54f923b6f7bac01166c093e5e81f50f0442ed6d9a03e58d0a5e0d76a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - astropy-base >=5.2,<8.dev0
    - ctapipe >=0.19.0,<0.24.0.dev0
    - protozfits >=2.6,<3.dev0
    - numpy >=1.20
    - scipy

test:
  imports:
    - ctapipe_io_lst
  commands:
    - pip check
    # check setuptools_scm provided a version
    - python -c "from ctapipe_io_lst import __version__; print(__version__)" | grep -v 0.0.0
    # check our event source is findable by ctapipe
    - python -c 'from ctapipe.io import EventSource; print(EventSource.non_abstract_subclasses())' | grep LSTEventSource

  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/ctapipe-io-lst/
  summary: ctapipe plugin for reading LST prototype files
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maxnoe
    - moralejo
